import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import CurrentNavbar from './components/layout.client'
import Footer from './components/Footer'
import type { Metadata } from "next";

export const metadata: Metadata = {   title: "Sieventic",   description: "Generated by create next app", };

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <CurrentNavbar/>        
        </div>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
