import { Inter } from "next/font/google";
import "../globals.css";
import Blognavbar from "../components/Blognavbar";
import type { Metadata } from "next";  
export const metadata: Metadata = {   title: "Sieventic",   description: "Generated by create next app", };

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
        <div>
          <Blognavbar/>
          {children}
        </div>
  );
}
